### ISSUE TITLE
Add a "funds raised" banner to website that tracks total Euros raised

### ISSUE THREAD

**Issue by willblev** [willblev/PCBakers#6]
We could have a banner which shows the total Euros raised so far at the top of the website... not sure if it will look cool or not, but perhaps there is another "simple" way to share our progress besides the blog posts?

@PaulaNietoG what are your thoughts?

**Comment by willblev** [comment]
This looks very promising: https://chartscss.org/components/data/
Not sure if it should go on the main page (index) or the about page...

**Comment by PaulaNietoG** [comment]
I think it's a good idea, I like this style that show the rounded amount of money either directly or when hovering:
![image](https://user-images.githubusercontent.com/36140522/176850465-17f1328e-a32d-4d3d-8135-cdd94e8b7d2d.png). 
I'd put it on home, next to the PCBakers logo. It would also be nice to add the month/year below each bar 😄

**Comment by willblev** [comment]
That's what I was thinking too- using some of the animation/mouseover styles to make it _fancy_, then we just need to update the table with the new info once a month and this library takes care of the rest in css. There were two types of visualizations which I thought could work:
1. the **column** plot would be nice to show the month-by-month breakdown  (the one you mentioned) 
2. the **area** plot may be better to show the cumulative funds raised since PCBakers began, maybe making the mouseover for each month reveal the amount raised in that month? Not sure if it's possible but we can experiment.
![Screenshot from 2022-07-01 11-21-28](https://user-images.githubusercontent.com/5909997/176866342-ba1c7354-0756-4844-881f-b24da9ec6e6e.png)

**Comment by willblev** [comment]
That's what I was thinking too- using some of the animation/mouseover styles to make it _fancy_, then we just need to update the table with the new info once a month and this library takes care of the rest in css. There were two types of visualizations which I thought could work:
1. the **column** plot would be nice to show the month-by-month breakdown  (the one you mentioned) 
2. the **area** plot may be better to show the cumulative funds raised since PCBakers began
![Screenshot from 2022-07-01 11-21-28](https://user-images.githubusercontent.com/5909997/176866342-ba1c7354-0756-4844-881f-b24da9ec6e6e.png), maybe making the mouseover on each month would reveal the amount raised in that month? Not sure if it's possible but we can experiment.
